### PR TITLE
Start a business in menu

### PR DESCRIPTION
**Pull request by patlaj**
Mostly just checking to see how it works…

### CODE REVIEW

**Comment by neoinsight** [comment]
Hmm We are a bit concerned that people may see the MVP folder (for example) in Master and think they should work on it in Master, when that's not the case. So there's not really any value in pushing all of this to Master and some risk. For prototyping, we think sticking to just the GH-pages branch is best. Ok?

**Comment by patlaj** [comment]
Hey - ah that was definitely not my intention. I'm still a git newbie. Is
it easily fixed?

**Comment by neoinsight** [comment]
Well, it's still a pull request that I haven't merged. Thought I would just leave it like that. Not sure how to make it go away.

**Comment by patlaj** [comment]
Ah ok - so hopefully there's one request that's putting all those files in
the wrong branch, and one where I added a file and made a small change to
the mega menu. Is it possible to deny one and accept the other?

Sorry about that - I was experimenting with the GitHub desktop client at
home and that branch merge thing was a single button with no confirmation
(which I thought was updating my local pages). Sigh

**Comment by neoinsight** [comment]
Hmm, I only see the branch merge, I can't seem to break out the menu one. You might be able to do so from your end.

**Pull request closed without merging**
